fix script

diff --git a/bin/run-hook b/bin/run-hook
--- a/bin/run-hook
+++ b/bin/run-hook
@@ -15,13 +15,17 @@ SCRIPTS=$($bin scripts "$hook")
 # Make newlines the only separator
 IFS=$'\n'
 
-# Run each script
+# Set the exit code to 0. If any script fails,
+# this will then be set to that exit code
 exit_code=0
+
+# Run each script
 for SCRIPT in $SCRIPTS; do
     eval "$SCRIPT"
     last_exit_code=$?
     if [ $last_exit_code -ne 0 ]; then
         exit_code=$last_exit_code
-        exit $exit_code
     fi
 done
+
+exit $exit_code
